import { Monaco } from '@monaco-editor/react';
import { editor } from 'monaco-editor';

export const themeData: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    {
      background: '24292e',
      token: '',
    },
    {
      foreground: '747f8a',
      token: 'comment',
    },
    {
      foreground: '959da5',
      token: 'punctuation.definition.comment',
    },
    {
      foreground: '959da5',
      token: 'string.comment',
    },
    {
      foreground: 'c8e1ff',
      token: 'constant',
    },
    {
      foreground: 'c8e1ff',
      token: 'entity.name.constant',
    },
    {
      foreground: 'c8e1ff',
      token: 'variable.other.constant',
    },
    {
      foreground: 'c8e1ff',
      token: 'variable.language',
    },
    {
      foreground: 'b392f0',
      token: 'entity',
    },
    {
      foreground: 'b392f0',
      token: 'entity.name',
    },
    {
      foreground: 'f6f8fa',
      token: 'variable.parameter.function',
    },
    {
      foreground: '7bcc72',
      token: 'entity.name.tag',
    },
    {
      foreground: 'ea4a5a',
      token: 'keyword',
    },
    {
      foreground: 'ea4a5a',
      token: 'storage',
    },
    {
      foreground: 'ea4a5a',
      token: 'storage.type',
    },
    {
      foreground: 'f6f8fa',
      token: 'storage.modifier.package',
    },
    {
      foreground: 'f6f8fa',
      token: 'storage.modifier.import',
    },
    {
      foreground: 'f6f8fa',
      token: 'storage.type.java',
    },
    {
      foreground: '79b8ff',
      token: 'string',
    },
    {
      foreground: '79b8ff',
      token: 'punctuation.definition.string',
    },
    {
      foreground: '79b8ff',
      token: 'string punctuation.section.embedded source',
    },
    {
      foreground: 'c8e1ff',
      token: 'support',
    },
    {
      foreground: 'c8e1ff',
      token: 'meta.property-name',
    },
    {
      foreground: 'fb8532',
      token: 'variable',
    },
    {
      foreground: 'f6f8fa',
      token: 'variable.other',
    },
    {
      foreground: 'd73a49',
      fontStyle: 'bold italic underline',
      token: 'invalid.broken',
    },
    {
      foreground: 'd73a49',
      fontStyle: 'bold italic underline',
      token: 'invalid.deprecated',
    },
    {
      foreground: 'fafbfc',
      background: 'd73a49',
      fontStyle: 'italic underline',
      token: 'invalid.illegal',
    },
    {
      foreground: 'fafbfc',
      background: 'd73a49',
      fontStyle: 'italic underline',
      token: 'carriage-return',
    },
    {
      foreground: 'd73a49',
      fontStyle: 'bold italic underline',
      token: 'invalid.unimplemented',
    },
    {
      foreground: 'd73a49',
      token: 'message.error',
    },
    {
      foreground: 'f6f8fa',
      token: 'string source',
    },
    {
      foreground: 'c8e1ff',
      token: 'string variable',
    },
    {
      foreground: '79b8ff',
      token: 'source.regexp',
    },
    {
      foreground: '79b8ff',
      token: 'string.regexp',
    },
    {
      foreground: '79b8ff',
      token: 'string.regexp.character-class',
    },
    {
      foreground: '79b8ff',
      token: 'string.regexp constant.character.escape',
    },
    {
      foreground: '79b8ff',
      token: 'string.regexp source.ruby.embedded',
    },
    {
      foreground: '79b8ff',
      token: 'string.regexp string.regexp.arbitrary-repitition',
    },
    {
      foreground: '7bcc72',
      fontStyle: 'bold',
      token: 'string.regexp constant.character.escape',
    },
    {
      foreground: 'c8e1ff',
      token: 'support.constant',
    },
    {
      foreground: 'c8e1ff',
      token: 'support.variable',
    },
    {
      foreground: 'c8e1ff',
      token: 'meta.module-reference',
    },
    {
      foreground: 'fb8532',
      token: 'markup.list',
    },
    {
      foreground: '0366d6',
      fontStyle: 'bold',
      token: 'markup.heading',
    },
    {
      foreground: '0366d6',
      fontStyle: 'bold',
      token: 'markup.heading entity.name',
    },
    {
      foreground: 'c8e1ff',
      token: 'markup.quote',
    },
    {
      foreground: 'f6f8fa',
      fontStyle: 'italic',
      token: 'markup.italic',
    },
    {
      foreground: 'f6f8fa',
      fontStyle: 'bold',
      token: 'markup.bold',
    },
    {
      foreground: 'c8e1ff',
      token: 'markup.raw',
    },
    {
      foreground: 'b31d28',
      background: 'ffeef0',
      token: 'markup.deleted',
    },
    {
      foreground: 'b31d28',
      background: 'ffeef0',
      token: 'meta.diff.header.from-file',
    },
    {
      foreground: 'b31d28',
      background: 'ffeef0',
      token: 'punctuation.definition.deleted',
    },
    {
      foreground: '176f2c',
      background: 'f0fff4',
      token: 'markup.inserted',
    },
    {
      foreground: '176f2c',
      background: 'f0fff4',
      token: 'meta.diff.header.to-file',
    },
    {
      foreground: '176f2c',
      background: 'f0fff4',
      token: 'punctuation.definition.inserted',
    },
    {
      foreground: 'b08800',
      background: 'fffdef',
      token: 'markup.changed',
    },
    {
      foreground: 'b08800',
      background: 'fffdef',
      token: 'punctuation.definition.changed',
    },
    {
      foreground: '2f363d',
      background: '959da5',
      token: 'markup.ignored',
    },
    {
      foreground: '2f363d',
      background: '959da5',
      token: 'markup.untracked',
    },
    {
      foreground: 'b392f0',
      fontStyle: 'bold',
      token: 'meta.diff.range',
    },
    {
      foreground: 'c8e1ff',
      token: 'meta.diff.header',
    },
    {
      foreground: '0366d6',
      fontStyle: 'bold',
      token: 'meta.separator',
    },
    {
      foreground: '0366d6',
      token: 'meta.output',
    },
    {
      foreground: 'ffeef0',
      token: 'brackethighlighter.tag',
    },
    {
      foreground: 'ffeef0',
      token: 'brackethighlighter.curly',
    },
    {
      foreground: 'ffeef0',
      token: 'brackethighlighter.round',
    },
    {
      foreground: 'ffeef0',
      token: 'brackethighlighter.square',
    },
    {
      foreground: 'ffeef0',
      token: 'brackethighlighter.angle',
    },
    {
      foreground: 'ffeef0',
      token: 'brackethighlighter.quote',
    },
    {
      foreground: 'd73a49',
      token: 'brackethighlighter.unmatched',
    },
    {
      foreground: 'd73a49',
      token: 'sublimelinter.mark.error',
    },
    {
      foreground: 'fb8532',
      token: 'sublimelinter.mark.warning',
    },
    {
      foreground: '6a737d',
      token: 'sublimelinter.gutter-mark',
    },
    {
      foreground: '79b8ff',
      fontStyle: 'underline',
      token: 'constant.other.reference.link',
    },
    {
      foreground: '79b8ff',
      fontStyle: 'underline',
      token: 'string.other.link',
    },
  ],
  colors: {
    'activityBar.background': '#1D252C',
    'activityBar.border': '#333F4A',
    'activityBar.dropBackground': '#333F4A',
    'activityBar.foreground': '#fff',
    'activityBarBadge.background': '#11a5ff',
    'activityBarBadge.foreground': '#000',
    'badge.background': '#11a5ff',
    'badge.foreground': '#000',
    'button.background': '#1D252C',
    'button.foreground': '#fff',
    'button.hoverBackground': '#11a5ff',
    contrastActiveBorder: '#fff',
    contrastBorder: '#ffffff00',
    'debugExceptionWidget.background': '#1D252C',
    'debugExceptionWidget.border': '#aaa',
    'debugToolBar.background': '#1D252C',
    descriptionForeground: '#aaa',
    'diffEditor.insertedTextBackground': '#3ad90011',
    'diffEditor.insertedTextBorder': '#3ad90055',
    'diffEditor.removedTextBackground': '#ee3a4311',
    'diffEditor.removedTextBorder': '#ee3a4355',
    'dropdown.background': '#1D252C',
    'dropdown.border': '#15232d',
    'dropdown.foreground': '#fff',
    'editor.background': '#1D252C',
    // 'editor.background': '#1D252C',
    'editor.foreground': '#B7C5D3',
    'editor.findMatchBackground': '#b7c5d380',
    'editor.findMatchHighlightBackground': '#b7c5d330',
    'editor.findRangeHighlightBackground': '#243E51',
    'editor.hoverHighlightBackground': '#313a42',
    'editor.inactiveSelectionBackground': '#313a42',
    'editor.lineHighlightBackground': '#28313a',
    'editor.lineHighlightBorder': '#28313a',
    'editor.rangeHighlightBackground': '#28313a',
    'editor.selectionBackground': '#313a42',
    'editor.selectionHighlightBackground': '#28323a',
    'editor.wordHighlightStrongBackground': '#41505e',
    'editor.wordHighlightBackground': '#313a42',
    'editorBracketMatch.background': '#3d454d',
    'editorBracketMatch.border': '#68A1F0',
    'editorCodeLens.foreground': '#aaa',
    // "editorCursor.foreground": "#11a5ff",
    'editorCursor.foreground': '#008cff',
    'editorError.border': '#333F4A',
    'editorError.foreground': '#e27e8d',
    'editorGutter.background': '#1D252C',
    'editorGutter.addedBackground': '#8bd49c',
    'editorGutter.deletedBackground': '#e27e8d',
    'editorGutter.modifiedBackground': '#26506D',
    'editorGroup.background': '#1D252C',
    'editorGroup.border': '#1D252C',
    'editorGroup.dropBackground': '#333F4A',
    'editorGroupHeader.noTabsBackground': '#1D252C',
    'editorGroupHeader.tabsBackground': '#1D252C',
    'editorGroupHeader.tabsBorder': '#15232d',
    'editorHoverWidget.background': '#15232d',
    'editorHoverWidget.border': '#333F4A',
    'editorIndentGuide.background': '#41505E',
    'editorLineNumber.foreground': '#41505E',
    'editorLink.activeForeground': '#aaa',
    'editorMarkerNavigation.background': '#1D252C',
    'editorMarkerNavigationError.background': '#d95468',
    'editorMarkerNavigationWarning.background': '#f9b97f',
    'editorOverviewRuler.border': '#333F4A',
    'editorOverviewRuler.commonContentForeground': '#efe99455',
    'editorOverviewRuler.currentContentForeground': '#ee3a4355',
    'editorOverviewRuler.incomingContentForeground': '#3ad90055',
    'editorRuler.foreground': '#1F4662',
    'editorSuggestWidget.background': '#222A31',
    'editorSuggestWidget.border': '#15232d',
    'editorSuggestWidget.foreground': '#D1DFED',
    'editorSuggestWidget.highlightForeground': '#11a5ff',
    'editorSuggestWidget.selectedBackground': '#333F4A',
    'editorWarning.border': '#ffffff00',
    'editorWarning.foreground': '#efe994',
    'editorWhitespace.foreground': '#ffffff1a',
    'editorWidget.background': '#15232d',
    'editorWidget.border': '#333F4A',
    errorForeground: '#e27e8d',
    'extensionButton.prominentBackground': '#70c1f3',
    'extensionButton.prominentForeground': '#000',
    'extensionButton.prominentHoverBackground': '#11a5ff',
    focusBorder: '#333F4A',
    foreground: '#aaa',
    'input.background': '#1D252C',
    'input.border': '#333F4A',
    'input.foreground': '#b7c5d3',
    'input.placeholderForeground': '#aaa',
    'inputOption.activeBorder': '#333F4A',
    'inputValidation.errorBackground': '#e27e8d',
    'inputValidation.errorBorder': '#d95468',
    'inputValidation.infoBackground': '#5ec4ff',
    'inputValidation.infoBorder': '#539afc',
    'inputValidation.warningBackground': '#efe994',
    'inputValidation.warningBorder': '#f9b97f',
    'list.activeSelectionBackground': '#1D252C',
    'list.activeSelectionForeground': '#aaa',
    'list.dropBackground': '#333F4A',
    'list.focusBackground': '#333F4A',
    'list.focusForeground': '#aaa',
    'list.highlightForeground': '#11a5ff',
    'list.hoverBackground': '#1D252C',
    'list.hoverForeground': '#aaa',
    'list.inactiveSelectionBackground': '#333F4A',
    'list.inactiveSelectionForeground': '#aaa',
    'merge.border': '#ffffff00',
    'merge.commonContentBackground': '#ffffff00',
    'merge.commonHeaderBackground': '#ffffff00',
    'merge.currentContentBackground': '#ffffff00',
    'merge.currentHeaderBackground': '#ffffff00',
    'merge.incomingContentBackground': '#ffffff00',
    'merge.incomingHeaderBackground': '#ffffff00',
    'notification.background': '#efe994',
    'notification.buttonBackground': '#5ec4ff',
    'notification.buttonForeground': '#fff',
    'notification.buttonHoverBackground': '#11a5ff',
    'notification.errorBackground': '#b62d65',
    'notification.errorForeground': '#fff',
    'notification.foreground': '#000',
    'notification.infoBackground': '#5ec4ff',
    'notification.infoForeground': '#fff',
    'notification.warningBackground': '#11a5ff',
    'notification.warningForeground': '#000',
    'panel.background': '#171d23',
    'panel.border': '#171d23',
    'panelTitle.activeBorder': '#41505E',
    'panelTitle.activeForeground': '#41505E',
    'panelTitle.inactiveForeground': '#aaa',
    'peekView.border': '#333F4A',
    'peekViewEditor.background': '#1D252C',
    'peekViewEditor.matchHighlightBackground': '#15232d',
    'peekViewEditorGutter.background': '#333F4A',
    'peekViewResult.background': '#15232d',
    'peekViewResult.fileForeground': '#aaa',
    'peekViewResult.lineForeground': '#fff',
    'peekViewResult.matchHighlightBackground': '#333F4A',
    'peekViewResult.selectionBackground': '#333F4A',
    'peekViewResult.selectionForeground': '#fff',
    'peekViewTitle.background': '#15232d',
    'peekViewTitleDescription.foreground': '#aaa',
    'peekViewTitleLabel.foreground': '#008b94',
    'pickerGroup.border': '#333F4A',
    'pickerGroup.foreground': '#aaa',
    'progressBar.background': '#008b94',
    'scrollbar.shadow': '#00000000',
    'scrollbarSlider.activeBackground': '#333F4A',
    'scrollbarSlider.background': '#41505E',
    'scrollbarSlider.hoverBackground': '#41505E',
    'selection.background': '#027dff',
    'sideBar.background': '#171d23',
    'sideBar.border': '#1D252C',
    'sideBar.foreground': '#aaa',
    'sideBarSectionHeader.background': '#1D252C',
    'sideBarSectionHeader.foreground': '#aaaaaa',
    'sideBarTitle.foreground': '#aaaaaa',
    'statusBar.background': '#171d23',
    'statusBar.border': '#1D252C',
    'statusBar.debuggingBackground': '#171d23',
    'statusBar.debuggingForeground': '#333F4A',
    'statusBar.foreground': '#aaa',
    'statusBar.noFolderBackground': '#171d23',
    'statusBar.noFolderForeground': '#aaa',
    'statusBarItem.activeBackground': '#5ec4ff',
    'statusBarItem.hoverBackground': '#333F4A',
    'statusBarItem.prominentBackground': '#171d23',
    'statusBarItem.prominentHoverBackground': '#333F4A',
    'tab.activeBackground': '#1D252C',
    'tab.activeForeground': '#fff',
    'tab.border': '#171d23',
    'tab.activeBorder': '#1D252C',
    'tab.inactiveBackground': '#171d23',
    'tab.inactiveForeground': '#aaa',
    'tab.unfocusedActiveForeground': '#aaa',
    'tab.unfocusedInactiveForeground': '#aaa',
    'terminal.ansiBlack': '#505050',
    'terminal.ansiRed': '#FF5370',
    'terminal.ansiGreen': '#0cfa83',
    'terminal.ansiYellow': '#ff8308',
    'terminal.ansiBlue': '#1e8eff',
    'terminal.ansiMagenta': '#8e37ff',
    'terminal.ansiCyan': '#03c9dd',
    'terminal.ansiWhite': '#d0d0d0',
    'terminal.ansiBrightBlack': '#6a6a6a',
    'terminal.ansiBrightRed': '#ff869a',
    'terminal.ansiBrightGreen': '#3efb9d',
    'terminal.ansiBrightYellow': '#ffb66e',
    'terminal.ansiBrightBlue': '#84c1ff',
    'terminal.ansiBrightMagenta': '#ab6aff',
    'terminal.ansiBrightCyan': '#17e7fc',
    'terminal.ansiBrightWhite': '#ffffff',
    'terminal.background': '#171d23',
    'terminal.foreground': '#b4e1fd',
    'terminalCursor.background': '#0883ff',
    'terminalCursor.foreground': '#0883ff',
    'textBlockQuote.background': '#171d23',
    'textBlockQuote.border': '#171d23',
    'textCodeBlock.background': '#171d23',
    'textLink.activeForeground': '#718ca1',
    'textLink.foreground': '#718ca1',
    'textPreformat.foreground': '#1D252C',
    'textSeparator.foreground': '#1D252C',
    'titleBar.activeBackground': '#171d23',
    'titleBar.activeForeground': '#ffffff',
    'titleBar.inactiveBackground': '#1D252C',
    'titleBar.inactiveForeground': '#ffffff33',
    'walkThrough.embeddedEditorBackground': '#1D252C',
    'welcomePage.buttonBackground': '#1D252C',
    'welcomePage.buttonHoverBackground': '#333F4A',
    'widget.shadow': '#00000026',
  },
};
// fontFamily: 'Arial',
export const createTheme = (monaco: Monaco) => {
  const themeId = 'shaderkit';
  monaco.editor.defineTheme(themeId, themeData);
  monaco.editor.setTheme(themeId);

  // monaco.editor.EditorOptions.fontFamily = 'fira-code';
};
